array_layout = "Block"
chain_indent = "Block"
closure_block_indent_threshold = -1
control_brace_style = "ClosingNextLine"
fn_args_layout = "Block"
fn_args_paren_newline = false
fn_brace_style = "PreferSameLine"
fn_call_style = "Block"
fn_empty_single_line = false
item_brace_style = "PreferSameLine"
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
spaces_around_ranges = true
tab_spaces = 2
use_try_shorthand = true
trailing_comma = "Never"
